### PR TITLE
Refactoring and fixes

### PR DESCRIPTION
**Pull request by jslegendre**
Added support for multi word titles, subtitles, messages. Refactored for easier expandability. Simplified CFString conversion. Added check for title as one is required for NSUserNotification.

What is left to do:
- Find a way to dynamically set bundle id
- Move NSUserNotification init and setters to separate file for better organization and more modular usability
- See what else can be further refactored
- Write tests

### CODE REVIEW

**Comment by bmcculley** [comment]
That's great! Makes me realize I really don't know c at all looking through that. Do you want to move development back to your original repo? I wasn't sure if you would be interested in going further or just wanted to keep it as more of an example.

I created issues for the what's left list. What should we use to create the tests? Any preferences?

**Comment by jslegendre** [comment]
Hey, thanks!  Most of this stuff isn't really C though, it is behind-the-scenes Objective-C.  I wouldn't really worry about not knowing this stuff if you just want to learn C. Learn this stuff if you want to get into macOS hacking (I can point you in the right direction if you do). 

I think we should keep this repo for this project.  My OG repo is basically the result of a research project I spent way too much time on.  I couldn't find anyone doing Objective-C method swizzling in C or C++ anywhere so I jumped on the chance to do something new. 

Thank you for creating those issues btw.  As far as tests go I am not entirely sure how to approach this one. My first thought would be to write the tests in Objective-C as some methods will need to verify some obj-c objects were created correctly.  It would be possible to verify this in C, it would take time.  Python has a nice obj-c FFI too so that is something to consider. It might take some trial and error to figure out what would work best for this very unique case.

**Comment by jslegendre** [comment]
Would it be possible to make me a project owner/moderator so I can create branches and assign issues to myself?

**Comment by bmcculley** [comment]
Just added you as a collaborator.

Yes definitely if you have some resources I would love to have a look at them. I was pretty much just poking around apple's documentation and trying stuff to see what worked. That was slow going so I'm not sure that's the best way to go.

And ok cool, I thought about doing a pull request to your original but then was like nah leave that as an example. But then, I started feeling like I was stealing this away. lol

I like the idea of using python to test, seems like it could be an interesting way to go.

Also, I wanted to ask about making changes/adding new stuff. I just added the ability to pipe data into the message, but I was thinking maybe I should put it in a branch and get your opinion/blessing on it first before adding to the master. Does that sound like a good way to do things?

**Comment by jslegendre** [comment]
You should definitely create an 'enhancement' issue, make a branch, and create a PR from there.  I'm looking forward to reviewing it. 

We can further discuss testing tools in the issue.  I will be posting an example from a past project on testing C with python.

P.S. Looking at Apple documentation is actually a pretty good place to start.  Not the most interesting or quickest way, but it will definitely set you up with a solid foundation.

**Comment by bmcculley** [comment]
Awesome, thank you. I wasn't sure if I was missing an easier way. Also, I finally looked up "method swizzling". Not sure why I hadn't thought to do that earlier but it looks like that turned up a good amount of interesting reading.

**Pull request merged**
